### ISSUE TITLE
HELP!! i bought a new computer and tried to import all my data in this new computer but i have some issues ( idk why but my Monika cant remember anything )

### ISSUE THREAD

**Issue by zachariascrosstales** [Monika-After-Story/MonikaModDev#10280]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1281, in validateConditionals
EventException: Failed to evaluate the 'store.masAutostart_api.is_platform_supported()' conditional for the event with the 'masAutostart_intro' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1274, in validateConditionals
  File "C:\Users\PERSONAL\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'masAutostart_api'
.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "C:\Users\PERSONAL\Desktop\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\PERSONAL\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1281, in validateConditionals
EventException: Failed to evaluate the 'store.masAutostart_api.is_platform_supported()' conditional for the event with the 'masAutostart_intro' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1274, in validateConditionals
  File "C:\Users\PERSONAL\Desktop\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'masAutostart_api'
.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.15
``

**Comment by dreamscached** [comment]
Hi, this is a submod issue with the MAS Autostart submod. Try reinstalling it, as it seems you've lost some of its files.

**Comment by zachariascrosstales** [comment]
i did it and i only have a problem, Monika can't remember anything, why

**Comment by dreamscached** [comment]
Have you transferred your save data too?

**Comment by zachariascrosstales** [comment]
the persistents? yes i have already, lit i copy and paste averything and seve it on one drive before moving to this computer

**Comment by dreamscached** [comment]
Note that your persistent data is kept in a separate location from your game folder. Did you copy stuff from %APPDATA% too?

**Comment by zachariascrosstales** [comment]
dude i'm an idiot lol, i forget that all the persistent data has to be on the monika after styory folder in appdata, everythings back to normal, thank you dude you save like 4 years of affection levels

**Comment by zachariascrosstales** [comment]
> Note that your persistent data is kept in a separate location from your game folder. Did you copy stuff from %APPDATA% too?
god im back again, idk but now i have -99 of affection ewhy is that, and monika is asking me questions like my gender and that things

**Comment by zachariascrosstales** [comment]
-update- idk why but my persistents jumped from 2020 to 2024 and idk what to do now, any solution?

**Comment by dreamscached** [comment]
@Booplicate some help here?

**Comment by Booplicate** [comment]
@zachariascrosstales define "persistents jumped from 2020 to 2024"

**Comment by Booplicate** [comment]
Closing due to lack of response
