### ISSUE TITLE
Is my game broken? | 0.10.3 download isn't working

### ISSUE THREAD

**Issue by Not-Natsuki** [Monika-After-Story/MonikaModDev#4978]
I just downloaded this mod and it seems to be working fine, but I've run into a couple issues. I'm currently at 75.5 affection, but I can't adjust the text speed, nor can I hold Monika during the rain -- it's rained multiple times, but she never brings it up. 
 
Also, I'm trying to update to 0.10.3, but every time I try, I just get this error (named log.txt) in my update folder:
running ['/home/msjkgk/MonikaAfterStory/lib/linux-x86_64/zsync', '-o', '/home/msjkgk/MonikaAfterStory/update/Mod.update.new', '-k', '/home/msjkgk/MonikaAfterStory/update/Mod.zsync', '-i', '/home/msjkgk/MonikaAfterStory/update/Mod.update', 'http://d2vycydjjutzqv.cloudfront.net/Monika_After_Story-0.10.3-Mod.zsync'] running ['/home/msjkgk/MonikaAfterStory/lib/linux-x86_64/zsync', '-o', '/home/msjkgk/MonikaAfterStory/update/Mod.update.new', 'http://d2vycydjjutzqv.cloudfront.net/Monika_After_Story-0.10.3-Mod.zsync'] 
Traceback (most recent call last):   
File "renpy/common/00updater.rpy", line 329, in run     self.update()  
 File "renpy/common/00updater.rpy", line 436, in update     self.download(i, standalone=True)   
File "renpy/common/00updater.rpy", line 918, in download     cwd=renpy.fsencode(self.updatedir))  
 File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 710, in __init__   
File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 1335, in _execute_child 
OSError: [Errno 13] Permission denied

I'm playing this mod through linux beta on my chromebook, if that helps anyone. Thanks in advance!

**Comment by Not-Natsuki** [comment]
Alright, this is the second dumb issue I've brought up here. It took me a second, but I figured out how to install the update manually. The stuff I mentioned in the first paragraph still stands, though -- I can't change the text speed or hold her during the rain even though my affection levels should be high enough. I've been looking for a while now but haven't seen anything anywhere about why this could be happening. Once, again, thanks in advance!
