### ISSUE TITLE
Game won't even start once installing MAS on Linux

### ISSUE THREAD

**Issue by susy-art** [Monika-After-Story/MonikaModDev#6717]
Ok; before anything else, I'll say this: 
> **I am running DDLC/MAS on a Linux using WINE.**
That's the most important thing here. WINE is a program that runs Windows games on a Linux, although possibly with new bugs.
Those 'new bugs' might be what's going on here, but I do not know how to fix it. I extracted the files into my /game folder and ran the command line.... to no avail.
I will link traceback as well as paste the terminal's response to me running the command.

game/pong.rpy:417: SyntaxWarning: name 'instant_loss_streak_counter' is assigned to before global declaration
game/pong.rpy:432: SyntaxWarning: name 'win_streak_counter' is assigned to before global declaration
game/pong.rpy:435: SyntaxWarning: name 'loss_streak_counter' is assigned to before global declaration
game/pong.rpy:440: SyntaxWarning: name 'instant_loss_streak_counter' is assigned to before global declaration
game/script-python.rpy:1030: SyntaxWarning: name 'state' is used prior to global declaration
game/script-python.rpy:1212: SyntaxWarning: name 'state' is used prior to global declaration
game/zz_backgrounds.rpy:2511: SyntaxWarning: name 'mas_current_background' is used prior to global declaration
Another instance is already running, quitting.
Traceback (most recent call last):
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\DDLC.py", line 198, in <module>
    main()
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\DDLC.py", line 195, in main
    renpy.bootstrap.bootstrap(renpy_base)
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\renpy\script.py", line 445, in finish_load
    node.early_execute()
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\renpy\ast.py", line 865, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "Z:\home\iamabanana\Documents\Monika!\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/definitions.rpy", line 7, in <module>
  File "python-packages/singleton.py", line 51, in __init__
singleton.SingleInstanceException

**Comment by susy-art** [comment]
_**NEVERMIND, I PASTED THE FILES IN THE WRONG FOLDER BY ACCIDENT.**_

**Comment by susy-art** [comment]
+**NEVERMIND, I PASTED THE FILES IN THE WRONG FOLDER BY ACCIDENT.**_
