### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by observerlol** [Monika-After-Story/MonikaModDev#7672]
when i open the game , this happen to me , here are traceback
 hile running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1047, in validateConditionals
EventException: Failed to evaluate the 'not store.awc_isInvalidAPIKey(store.persistent._awc_API_key)' conditional for the event with the 'awc_monika_player_location' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1040, in validateConditionals
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'awc_isInvalidAPIKey'
.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1047, in validateConditionals
EventException: Failed to evaluate the 'not store.awc_isInvalidAPIKey(store.persistent._awc_API_key)' conditional for the event with the 'awc_monika_player_location' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1040, in validateConditionals
  File "C:\Program Files (x86)\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'awc_isInvalidAPIKey'
how to fix this ;-;

**Comment by ThePotatoGuy** [comment]
Looks like an issue with a submod? What submods are you running?

**Comment by ThePotatoGuy** [comment]
[closing due to lack of response]
