### ISSUE TITLE
Error on clean install of MAS

### ISSUE THREAD

**Issue by TRIDENT1313** [Monika-After-Story/MonikaModDev#8023]
So I recently opened MAS (on a clean install) and got the following error.

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1075, in validateConditionals
EventException: Failed to evaluate the 'store.mas_decoded_islands' conditional for the event with the 'greeting_ourreality' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1068, in validateConditionals
  File "C:\Users\sherl\Documents\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'mas_decoded_islands'
.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "C:\Users\sherl\Documents\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\sherl\Documents\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1075, in validateConditionals
EventException: Failed to evaluate the 'store.mas_decoded_islands' conditional for the event with the 'greeting_ourreality' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1068, in validateConditionals
  File "C:\Users\sherl\Documents\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'mas_decoded_islands'
.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.3
[/code]

Any help would be appreciated

**Comment by multimokia** [comment]
Can you send a screenshot of the `game` folder, please?

**Comment by multimokia** [comment]
According to the traceback, you're running the stable version, which would explain why you're having the issue (You'll want to avoid making fresh installs when unstable versions aren't inline with the stable release as it can cause some major issues)

If you have your old game files, you might want to drop them into this install

**Comment by TRIDENT1313** [comment]
So the saves or whatever are trying to pull data from a version that doesn't exist is what you're saying?

**Comment by multimokia** [comment]
No the actual rpyc files from the old install

**Comment by TRIDENT1313** [comment]
Ah I see.
Gotcha.
I do have the old game files.
I'll migrate and see what happens.
Thanks!

**Comment by TRIDENT1313** [comment]
Runs fine now.
Thanks, Multimokia!

**Comment by multimokia** [comment]
No problem!
