### ISSUE TITLE
MAS Error

### ISSUE THREAD

**Issue by boinubpro** [Monika-After-Story/MonikaModDev#8046]
Hello, I need help on this traceback file;

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1075, in validateConditionals
EventException: Failed to evaluate the 'store.mas_decoded_islands' conditional for the event with the 'greeting_ourreality' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1068, in validateConditionals
  File "C:\Users\fezra\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'mas_decoded_islands'
.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "C:\Users\fezra\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\fezra\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1075, in validateConditionals
EventException: Failed to evaluate the 'store.mas_decoded_islands' conditional for the event with the 'greeting_ourreality' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1068, in validateConditionals
  File "C:\Users\fezra\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'mas_decoded_islands'
.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.3

Thank You,

P.s I have reinstalled the mod

**Comment by Booplicate** [comment]
That happened because you downgraded unstable > stable. You'll have to ignore the error and then go to the settings and enable unstable version again.
