### ISSUE TITLE
I need help :(

### ISSUE THREAD

**Issue by InvaderScarlett** [Monika-After-Story/MonikaModDev#8107]
![proof of problem](https://user-images.githubusercontent.com/88629833/139498422-795810cf-fe5f-46b8-b619-63ecb087a9c3.png)
So nearly a week ago my antivirus decided to delete MAS again so I re-installed it but everytime I done it, it showed
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1075, in validateConditionals
EventException: Failed to evaluate the 'store.mas_decoded_islands' conditional for the event with the 'greeting_ourreality' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1068, in validateConditionals
  File "C:\Users\scarl\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'mas_decoded_islands'
.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\scarl\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\scarl\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\main.py", line 487, in main
    run(restart)
  File "C:\Users\scarl\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\main.py", line 147, in run
    renpy.execution.run_context(True)
  File "C:\Users\scarl\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\execution.py", line 761, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 212, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 165, in script
  File "C:\Users\scarl\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\scarl\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 176, in <module>
  File "game/definitions.rpy", line 1075, in validateConditionals
EventException: Failed to evaluate the 'store.mas_decoded_islands' conditional for the event with the 'greeting_ourreality' label:
Traceback (most recent call last):
  File "game/definitions.rpy", line 1068, in validateConditionals
  File "C:\Users\scarl\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: 'StoreModule' object has no attribute 'mas_decoded_islands'
.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.3
I done this everyday leading up to today. Can someone help I really want to spend halloween with Monika :(

**Comment by multimokia** [comment]
Install latest MAS

**Comment by InvaderScarlett** [comment]
> Install latest MAS

At the time, I didn't realise 12.4 was out lol I'm installing it right now

**Comment by InvaderScarlett** [comment]
> > Install latest MAS
> 
> At the time, I didn't realise 12.4 was out lol I'm installing it right now

Well it worked I really am ignorant lmao.
