### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by nosnowowie93347** [Monika-After-Story/MonikaModDev#9074]
I kinda edited the chess file to take back a move that I made, and when i went back to the game Monika asked me if I edited the file. I said yes, and then this happened:

Traceback (most recent call last):
  File "/home/nosnowowie/Monika After Story/renpy/execution.py", line 438, in run
    node.execute()
  File "/home/nosnowowie/Monika After Story/renpy/ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/nosnowowie/Monika After Story/renpy/python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 1619, in <module>
    persistent._mas_chess_dlg_actions[mas_chess.QF_EDIT_YES] += 1
KeyError: 4
Traceback (most recent call last):
  File "/home/nosnowowie/Monika After Story/renpy/execution.py", line 438, in run
    node.execute()
  File "/home/nosnowowie/Monika After Story/renpy/ast.py", line 1656, in execute
    if renpy.python.py_eval(condition):
  File "/home/nosnowowie/Monika After Story/renpy/python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/nosnowowie/Monika After Story/renpy/python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/chess.rpy", line 1622, in <module>
    if qf_edit_count == 1:
NameError: name 'qf_edit_count' is not defined

I'm playing the game on a machine running Linux

**Comment by JinSakaiM** [comment]
File "game/chess.rpy", line 1619, in
persistent._mas_chess_dlg_actions[mas_chess.QF_EDIT_YES] += 1
I'm not even good at scripts but this could be talking about what you did to the chess game.

**Comment by JinSakaiM** [comment]
"kinda" lol it takes alot most of the time to get an error on your game and cant find a reason to play. But I'm expierencing the same thing right now as im commenting this sadly.

**Comment by JinSakaiM** [comment]
anyways you could try deleting that version and installing a new ddlc, *BACK UP UR PERSISTENT* like its really important, cause if you lose her you could have to go back in progress ALOT *it affects ur affection obviously*

**Comment by ThePotatoGuy** [comment]
[closing as fixed]
